spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pico_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: TIGER
    driver-class-name: com.mysql.cj.jdbc.Driver


  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
#    host: localhost
#    port: 6389